// export a constant called initialBookList which is an array of objects.
export const intialBookList = [
  {
    id: 0,
    title: "The Alchemist",
    author: "Paulo Coelho",
    imageUrl: "https://i.pravatar.cc/48?u=499476",
  },
  {
    id: 1,
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    imageUrl: "https://i.pravatar.cc/48?u=4994761",
  },
  {
    id: 2,
    title: "Harry Potter and the Philosopher's Stone",
    author: "J.K. Rowling",
    imageUrl: "https://i.pravatar.cc/48?u=4994762",
  },
  {
    id: 3,
    title: "The Lion, the Witch and the Wardrobe",
    author: "C.S. Lewis",
    imageUrl: "https://i.pravatar.cc/48?u=4994763",
  },
  {
    id: 4,
    title: "A Game of Thrones",
    author: "George R.R. Martin",
    imageUrl: "https://i.pravatar.cc/48?u=4994764",
  },
  {
    id: 5,
    title: "The Alchemist",
    author: "Paulo Coelho",
    imageUrl: "https://i.pravatar.cc/48?u=499476",
  },
  {
    id: 6,
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    imageUrl: "https://i.pravatar.cc/48?u=4994761",
  },
  {
    id: 7,
    title: "Harry Potter and the Philosopher's Stone",
    author: "J.K. Rowling",
    imageUrl: "https://i.pravatar.cc/48?u=4994762",
  },
  {
    id: 8,
    title: "The Lion, the Witch and the Wardrobe",
    author: "C.S. Lewis",
    imageUrl: "https://i.pravatar.cc/48?u=4994763",
  },
  {
    id: 9,
    title: "A Game of Thrones",
    author: "George R.R. Martin",
    imageUrl: "https://i.pravatar.cc/48?u=4994764",
  },
  {
    id: 10,
    title: "The Alchemist",
    author: "Paulo Coelho",
    imageUrl: "https://i.pravatar.cc/48?u=499476",
  },
  {
    id: 11,
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    imageUrl: "https://i.pravatar.cc/48?u=4994761",
  },
  {
    id: 12,
    title: "Harry Potter and the Philosopher's Stone",
    author: "J.K. Rowling",
    imageUrl: "https://i.pravatar.cc/48?u=4994762",
  },
  {
    id: 13,
    title: "The Lion, the Witch and the Wardrobe",
    author: "C.S. Lewis",
    imageUrl: "https://i.pravatar.cc/48?u=4994763",
  },
  {
    id: 14,
    title: "A Game of Thrones",
    author: "George R.R. Martin",
    imageUrl: "https://i.pravatar.cc/48?u=4994764",
  },
  {
    id: 15,
    title: "The Alchemist",
    author: "Paulo Coelho",
    imageUrl: "https://i.pravatar.cc/48?u=499476",
  },
  {
    id: 16,
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    imageUrl: "https://i.pravatar.cc/48?u=4994761",
  },
  {
    id: 17,
    title: "Harry Potter and the Philosopher's Stone",
    author: "J.K. Rowling",
    imageUrl: "https://i.pravatar.cc/48?u=4994762",
  },
  {
    id: 18,
    title: "The Lion, the Witch and the Wardrobe",
    author: "C.S. Lewis",
    imageUrl: "https://i.pravatar.cc/48?u=4994763",
  },
  {
    id: 19,
    title: "A Game of Thrones",
    author: "George R.R. Martin",
    imageUrl: "https://i.pravatar.cc/48?u=4994764",
  },
  {
    id: 20,
    title: "A Game of Thrones",
    author: "George R.R. Martin",
    imageUrl: "https://i.pravatar.cc/48?u=4994764",
  },
  {
    id: 21,
    title: "The Alchemist",
    author: "Paulo Coelho",
    imageUrl: "https://i.pravatar.cc/48?u=499476",
  },
  {
    id: 22,
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    imageUrl: "https://i.pravatar.cc/48?u=4994761",
  },
  {
    id: 23,
    title: "Harry Potter and the Philosopher's Stone",
    author: "J.K. Rowling",
    imageUrl: "https://i.pravatar.cc/48?u=4994762",
  },
  {
    id: 24,
    title: "The Lion, the Witch and the Wardrobe",
    author: "C.S. Lewis",
    imageUrl: "https://i.pravatar.cc/48?u=4994763",
  },
  {
    id: 25,
    title: "A Game of Thrones",
    author: "George R.R. Martin",
    imageUrl: "https://i.pravatar.cc/48?u=4994764",
  },
  {
    id: 26,
    title: "The Alchemist",
    author: "Paulo Coelho",
    imageUrl: "https://i.pravatar.cc/48?u=499476",
  },
  {
    id: 27,
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    imageUrl: "https://i.pravatar.cc/48?u=4994761",
  },
  {
    id: 28,
    title: "Harry Potter and the Philosopher's Stone",
    author: "J.K. Rowling",
    imageUrl: "https://i.pravatar.cc/48?u=4994762",
  },
  {
    id: 29,
    title: "The Lion, the Witch and the Wardrobe",
    author: "C.S. Lewis",
    imageUrl: "https://i.pravatar.cc/48?u=4994763",
  },
  {
    id: 30,
    title: "A Game of Thrones",
    author: "George R.R. Martin",
    imageUrl: "https://i.pravatar.cc/48?u=4994764",
  },
  {
    id: 31,
    title: "The Alchemist",
    author: "Paulo Coelho",
    imageUrl: "https://i.pravatar.cc/48?u=499476",
  },
  {
    id: 32,
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    imageUrl: "https://i.pravatar.cc/48?u=4994761",
  },
  {
    id: 33,
    title: "Harry Potter and the Philosopher's Stone",
    author: "J.K. Rowling",
    imageUrl: "https://i.pravatar.cc/48?u=4994762",
  },
  {
    id: 34,
    title: "The Lion, the Witch and the Wardrobe",
    author: "C.S. Lewis",
    imageUrl: "https://i.pravatar.cc/48?u=4994763",
  },
  {
    id: 35,
    title: "A Game of Thrones",
    author: "George R.R. Martin",
    imageUrl: "https://i.pravatar.cc/48?u=4994764",
  },
  {
    id: 36,
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    imageUrl: "https://i.pravatar.cc/48?u=4994761",
  },
];

export const initialReadBooks = [
  {
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    imageUrl: "https://i.pravatar.cc/48?u=4994761",
  },
  {
    title: "Harry Potter and the Philosopher's Stone",
    author: "J.K. Rowling",
    imageUrl: "https://i.pravatar.cc/48?u=4994762",
  },
  {
    title: "The Lion, the Witch and the Wardrobe",
    author: "C.S. Lewis",
    imageUrl: "https://i.pravatar.cc/48?u=4994763",
  },
];
